version: '3'

services:
  groupme-discord-bot:
    build: .
    command: python bot/client.py
    volumes:
      - ./bot:/app/bot
    ports:
      - "8088:8088"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
